# prefix 뒤에 공백 한칸 꼭 필요함
# pattern 뒤에도 공백 필요


      
      
# spring.mvc.static-path-pattern=/static/** > /static/으로 시작하도록 강제함
# 위 방식은 application.properties에서 사용하는 방식


spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp